/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicatieCuPoze.alternativ;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Andrei
 */
public class Cal extends javax.swing.JPanel implements Runnable {

    private int number;

    /**
     * Creates new form Cal
     */
    public Cal(int n) {
        number = n;
        initComponents();
        l.setText("Cal " + n);
        try {
            p = new ImageProgressBar(ImageIO.read(getClass().getResource("horse3.gif")));
        } catch (IOException ex) {
            Logger.getLogger(Cal.class.getName()).log(Level.SEVERE, null, ex);
        }
        add(p);
    }

    public int getNumber() {
        return number;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l = new javax.swing.JLabel();
        p = new javax.swing.JProgressBar();
        lPic = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));
        setMinimumSize(new java.awt.Dimension(278, 110));
        setPreferredSize(new java.awt.Dimension(278, 110));
        setLayout(new java.awt.BorderLayout());

        l.setText("Cal XXXXX");
        l.setMaximumSize(new java.awt.Dimension(48, 30));
        l.setMinimumSize(new java.awt.Dimension(48, 30));
        l.setPreferredSize(new java.awt.Dimension(50, 105));
        add(l, java.awt.BorderLayout.LINE_START);

        p.setMaximum(200);
        p.setString("");
        p.setStringPainted(true);
        add(p, java.awt.BorderLayout.CENTER);

        lPic.setMaximumSize(new java.awt.Dimension(110, 110));
        lPic.setPreferredSize(new java.awt.Dimension(110, 110));
        add(lPic, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel l;
    private javax.swing.JLabel lPic;
    private javax.swing.JProgressBar p;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        lPic.setIcon(new ImageIcon(getClass().getResource("cal.gif")));
        try {
            ((ImageProgressBar)p).setI(ImageIO.read(ImageProgressBar.class.getResource("horse3.gif")));
        } catch (IOException ex) {
            Logger.getLogger(ImageProgressBar.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = p.getMinimum(); i <= p.getMaximum(); i++) {
            p.setValue(i);
            p.setString(i + " m");
            try {
                Thread.sleep((int) (Math.random() * 100));
            } catch (InterruptedException ex) {
                return;
            }
            //Color c = p.getForeground();
            if (Math.random() > 0.99) { // impiedicare
                Color c = p.getForeground();
                p.setForeground(Color.yellow);
                lPic.setIcon(new ImageIcon(getClass().getResource("waiting.jpg")));
                try {
                    Thread.sleep((int) (Math.random() * 500));

                } catch (InterruptedException ex) {
                    return;
                }
                lPic.setIcon(new ImageIcon(getClass().getResource("cal.gif")));
                p.setForeground(c);
            }
            if (Math.random() > 0.997) {    // ghinion fatal
                p.setForeground(Color.red);
                
                lPic.setIcon(new ImageIcon(getClass().getResource("rip.jpg")));
                try {
                    ((ImageProgressBar)p).setI(ImageIO.read(getClass().getResource("deadhorse2.gif")));
                    //p.setValue(p.getValue()+1);
                    p.repaint();
                } catch (IOException ex) {
                    Logger.getLogger(Cal.class.getName()).log(Level.SEVERE, null, ex);
                }
                return;
            }
        }
        p.setForeground(Color.green);
        lPic.setIcon(new ImageIcon(getClass().getResource("victorie.jpg")));
    }
}
