/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicatieCuPoze.alternativ;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author Andrei
 */
public class Cursa extends javax.swing.JFrame {
    private final int NRCAI=4;
    private List<Cal> cai = new ArrayList<Cal>();
    /**
     * Creates new form Cursa
     */
    public Cursa() {
        initComponents();
        for (int i = 0; i < NRCAI; i++) {
            Cal c = new Cal((int)(Math.random()*100));
            cai.add(c);
        }
        for(Cal c:cai){
            add(c);
        }
        add(bOrdonare);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bDii = new javax.swing.JButton();
        bOrdonare = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(NRCAI+2, 1, 0, 10));

        bDii.setText("Diiiiiiiiiii");
        bDii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDiiActionPerformed(evt);
            }
        });
        getContentPane().add(bDii);

        bOrdonare.setText("Ordonare");
        bOrdonare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrdonareActionPerformed(evt);
            }
        });
        getContentPane().add(bOrdonare);

        setSize(new java.awt.Dimension(468, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bOrdonareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrdonareActionPerformed
        Collections.sort(cai,new Comparator<Cal>(){

            @Override
            public int compare(Cal c1, Cal c2) {
                return c1.getNumber() - c2.getNumber();
            }
            
        });
        
        getContentPane().removeAll();
        add(bDii);
        for (Cal c:cai) {
            getContentPane().add(c);
        }
        add(bOrdonare);
        validate();
    }//GEN-LAST:event_bOrdonareActionPerformed

    private void bDiiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDiiActionPerformed
        for(Cal c:cai){
            new Thread(c).start();
        }
    }//GEN-LAST:event_bDiiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Cursa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDii;
    private javax.swing.JButton bOrdonare;
    // End of variables declaration//GEN-END:variables
}
